repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: clj-kondo
        name: Lint Clojure, ClojureScript, and EDN files
        language: system
        entry: clj-kondo --lint
        files: src/
  - repo: local
    hooks:
      - id: cljfmt
        name: Format Clojure code
        language: system
        entry: cljfmt --check
        files: src/
